import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { Navbar, Footer } from "@/UI";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Navbar
            links={[
              {
                text: "Precios",
                href: "/pricing",
              },
              {
                text: "Contratar",
                href: "/contact-sales",
              },
            ]}
          />
          <main className="min-h-screen text-balance">{children}</main>
        </NextUIProvider>
        <Footer />
      </body>
    </html>
  );
}
